# -*- coding: utf-8 -*-
"""ai_resume_c.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmecOLrZhp32RaHaniXGk49_8-7tn8lf

# Install required libraries
"""

!pip install PyPDF2 scikit-learn pandas

import os
import pandas as pd
from PyPDF2 import PdfReader
from google.colab import files
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""# Function to extract text from PDF"""

def extract_text_from_pdf(file_path):
    pdf = PdfReader(file_path)
    text = ""
    for page in pdf.pages:
        text += page.extract_text() or ""
    return text

"""# Upload PDF files"""

uploaded = files.upload()

"""# Extract text from PDFs"""

resumes = []
resume_names = []
for file_name in uploaded.keys():
    resume_text = extract_text_from_pdf(file_name)
    resumes.append(resume_text)
    resume_names.append(file_name)

"""# Input job description"""

job_description = input("Enter the job description: ")

"""# TF-IDF Vectorization"""

documents = [job_description] + resumes
vectorizer = TfidfVectorizer().fit_transform(documents)
vectors = vectorizer.toarray()

"""# Compute Cosine Similarity"""

job_vector = vectors[0]
resume_vectors = vectors[1:]
scores = cosine_similarity([job_vector], resume_vectors).flatten()

"""# Store results in DataFrame"""

results = pd.DataFrame({"Resume": resume_names, "Score": scores})
results = results.sort_values(by="Score", ascending=False)

"""# Save results"""

results.to_csv("ranked_resumes.csv", index=False)
print("Ranking completed! Download 'ranked_resumes.csv' from the file section.")

